// User
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const USER_LOADING = "USER_LOADING";
export const USERS_ERROR = "USERS_ERROR";
export const CLEAR_USER_ERRORS = "CLEAR_USER_ERRORS";
export const USER_LOADED = 'USER_LOADED';

// Alert
export const SET_ALERT = "SET_ALERT";

// Envelope
export const GET_ALL_ENVELOPES = "GET_ALL_ENVELOPES";
export const GET_ENVELOPE = 'GET_ENVELOPE';
export const ENVELOPES_ERROR = "ENVELOPES_ERROR";
export const ENVELOPE_LOADING = "ENVELOPE_LOADING";
export const ADD_ENVELOPE = "ADD_ENVELOPE";
export const CURRENT_ENVELOPE = "CURRENT_ENVELOPE";
export const CLEAR_ENVELOPE_ERRORS = "CLEAR_ENVELOPE_ERRORS";
export const ROLL_NUMBER = 'ROLL_NUMBER';